### ISSUE TITLE
ReferenceError: npm is not defined

### ISSUE THREAD

**Issue by yura121** [PsychicCat/random-crypto#1]
Please, check your code on https://www.npmjs.com/package/random-crypto

/random-crypto/index.js

``` javascript
            min = 0;
        }
npm
        //generate a buffer of 2 random bytes
        var buf = crypto.randomBytes(4);

```

Why has "npm" in the code?

**Comment by PsychicCat** [comment]
Ah, thanks for noticing that. I will fix, must have been typing in the wrong window and accidentally commit.

**Comment by yura121** [comment]
When do you plan to upgrade the package on npmjs.com?

**Comment by PsychicCat** [comment]
Updated now.

**Comment by yura121** [comment]
Thanks!
